// =========================================================
// FX Reference Module
//
// Purpose:
// - Read FX snapshots generated by GitHub Actions.
// - Use Receipt purchaseDate as the starting date.
// - If that date has no usable rate, move backward.
// - Never use a rate after the purchase date.
//
// FX is informational only.
// It must NOT overwrite Receipt total.
// It must NOT determine confirmation mismatch.
//
// Current home currency:
// - TWD
//
// Current supported networks:
// - Visa
// - Mastercard
// - JCB
// - Other -> First Bank fallback
// =========================================================


const FX_HOME_CURRENCY = 'TWD';


// Maximum number of calendar days to search backward.
//
// Example:
// purchaseDate = 2026-10-04
//
// try:
// 10/04
// 10/03
// 10/02
// ...
//
// This prevents unlimited HTTP requests when the Receipt
// predates the beginning of our FX archive.
const FX_MAX_LOOKBACK_DAYS = 10;


// Base path of the public FX archive.
//
// Because fx.js and data/ are both served from the same
// GitHub Pages site, use a root-relative repository path
// through URL resolution instead of hard-coding the
// GitHub Pages domain.
const FX_DATA_PATH = './data/fx';


// =========================================================
// Date helpers
// =========================================================

function parseDateOnly(dateString) {

  if (
    typeof dateString !== 'string' ||
    !/^\d{4}-\d{2}-\d{2}$/.test(dateString)
  ) {
    return null;
  }


  const [
    year,
    month,
    day
  ] = dateString
    .split('-')
    .map(Number);


  const date = new Date(
    Date.UTC(
      year,
      month - 1,
      day
    )
  );


  // Reject invalid calendar dates such as:
  // 2026-02-31
  if (
    date.getUTCFullYear() !== year ||
    date.getUTCMonth() !== month - 1 ||
    date.getUTCDate() !== day
  ) {
    return null;
  }


  return date;
}


function formatDateOnly(date) {

  const year =
    date.getUTCFullYear();

  const month =
    String(
      date.getUTCMonth() + 1
    ).padStart(2, '0');

  const day =
    String(
      date.getUTCDate()
    ).padStart(2, '0');


  return `${year}-${month}-${day}`;
}


function subtractDays(
  date,
  days
) {

  const result =
    new Date(
      date.getTime()
    );


  result.setUTCDate(
    result.getUTCDate() - days
  );


  return result;
}


// =========================================================
// Currency / network helpers
// =========================================================

function normalizeCurrency(currency) {

  return String(
    currency || ''
  )
    .trim()
    .toUpperCase();
}


function normalizeNetwork(network) {

  const normalized =
    String(
      network || ''
    )
      .trim()
      .toLowerCase();


  if (normalized === 'visa') {
    return 'visa';
  }


  if (
    normalized === 'mastercard' ||
    normalized === 'master card'
  ) {
    return 'mastercard';
  }


  if (normalized === 'jcb') {
    return 'jcb';
  }


  return 'other';
}


// =========================================================
// Load one FX snapshot
// =========================================================

async function loadFxSnapshot(
  dateString
) {

  const url =
    `${FX_DATA_PATH}/${dateString}.json`;


  try {

    const response =
      await fetch(
        url,
        {
          cache: 'no-store'
        }
      );


    if (!response.ok) {

      // 404 is normal.
      //
      // It can mean:
      // - weekend / missing archive
      // - date before archive started
      //
      // Do not treat it as an app error.
      return null;
    }


    const data =
      await response.json();


    if (
      !data ||
      typeof data !== 'object' ||
      !data.rates
    ) {
      return null;
    }


    return data;

  } catch (error) {

    console.warn(
      `FX snapshot unavailable: ${dateString}`,
      error
    );

    return null;
  }
}


// =========================================================
// Read one rate from one snapshot
// =========================================================

function getRateFromSnapshot(
  snapshot,
  currency,
  network
) {

  const currencyData =
    snapshot?.rates?.[currency];


  if (!currencyData) {
    return null;
  }


  const networkData =
    currencyData?.[network];


  if (!networkData) {
    return null;
  }


  const rate =
    Number(
      networkData.rate
    );


  if (
    !Number.isFinite(rate) ||
    rate <= 0
  ) {
    return null;
  }


  return {
    rate,

    source:
      networkData.source ||
      null,

    rateDate:
      networkData.rateDate ||
      null,

    rateType:
      networkData.rateType ||
      null,

    fallbackUsed:
      networkData.fallbackUsed === true,

    fetchedAt:
      networkData.fetchedAt ||
      snapshot.fetchedAt ||
      null
  };
}


// =========================================================
// Main FX lookup
// =========================================================

export async function getFxReference({
  purchaseDate,
  currency,
  network,
  maxLookbackDays =
    FX_MAX_LOOKBACK_DAYS
}) {

  const normalizedCurrency =
    normalizeCurrency(
      currency
    );


  const normalizedNetwork =
    normalizeNetwork(
      network
    );


  // -------------------------------------------------------
  // TWD does not need FX conversion.
  // -------------------------------------------------------

  if (
    normalizedCurrency ===
    FX_HOME_CURRENCY
  ) {

    return {
      available: false,
      reason: 'home-currency'
    };
  }


  // -------------------------------------------------------
  // Validate inputs
  // -------------------------------------------------------

  if (!normalizedCurrency) {

    return {
      available: false,
      reason: 'missing-currency'
    };
  }


  const startingDate =
    parseDateOnly(
      purchaseDate
    );


  if (!startingDate) {

    return {
      available: false,
      reason: 'invalid-purchase-date'
    };
  }


  const safeLookbackDays =
    Math.max(
      0,
      Math.min(
        Number.isFinite(
          Number(maxLookbackDays)
        )
          ? Math.floor(
              Number(maxLookbackDays)
            )
          : FX_MAX_LOOKBACK_DAYS,
        31
      )
    );


  // -------------------------------------------------------
  // Search purchaseDate first, then move backward.
  //
  // IMPORTANT:
  // We never search a date after purchaseDate.
  // -------------------------------------------------------

  for (
    let daysBack = 0;
    daysBack <= safeLookbackDays;
    daysBack += 1
  ) {

    const candidateDate =
      subtractDays(
        startingDate,
        daysBack
      );


    const candidateDateString =
      formatDateOnly(
        candidateDate
      );


    const snapshot =
      await loadFxSnapshot(
        candidateDateString
      );


    if (!snapshot) {
      continue;
    }


    const rateInfo =
      getRateFromSnapshot(
        snapshot,
        normalizedCurrency,
        normalizedNetwork
      );


    if (!rateInfo) {
      continue;
    }


    // -----------------------------------------------------
    // Determine the actual reference date.
    //
    // Visa / Mastercard:
    // Prefer their explicit rateDate.
    //
    // First Bank fallback:
    // There may be no historical rateDate, so use the
    // archive date of the snapshot we actually found.
    // -----------------------------------------------------

    const referenceDate =
      rateInfo.rateDate ||
      snapshot.archiveDate ||
      candidateDateString;


    return {
      available: true,

      purchaseDate,

      referenceDate,

      archiveDate:
        snapshot.archiveDate ||
        candidateDateString,

      currency:
        normalizedCurrency,

      homeCurrency:
        snapshot.homeCurrency ||
        FX_HOME_CURRENCY,

      network:
        normalizedNetwork,

      rate:
        rateInfo.rate,

      source:
        rateInfo.source,

      rateType:
        rateInfo.rateType,

      fallbackUsed:
        rateInfo.fallbackUsed,

      fetchedAt:
        rateInfo.fetchedAt,

      daysBack
    };
  }


  // -------------------------------------------------------
  // Nothing available within the permitted lookback.
  // -------------------------------------------------------

  return {
    available: false,

    reason:
      'no-reference-rate',

    purchaseDate,

    currency:
      normalizedCurrency,

    network:
      normalizedNetwork,

    maxLookbackDays:
      safeLookbackDays
  };
}


// =========================================================
// Conversion helper
// =========================================================

export function convertToTwd(
  foreignAmount,
  rate
) {

  const amount =
    Number(
      foreignAmount
    );


  const numericRate =
    Number(
      rate
    );


  if (
    !Number.isFinite(amount) ||
    !Number.isFinite(numericRate) ||
    numericRate <= 0
  ) {
    return null;
  }


  return (
    amount *
    numericRate
  );
}


// =========================================================
// Formatting helpers
// =========================================================

export function formatFxDate(
  dateString
) {

  const date =
    parseDateOnly(
      dateString
    );


  if (!date) {
    return '';
  }


  return [
    date.getUTCFullYear(),

    String(
      date.getUTCMonth() + 1
    ).padStart(2, '0'),

    String(
      date.getUTCDate()
    ).padStart(2, '0')
  ].join('/');
}


export function formatFxRate(
  rate
) {

  const numericRate =
    Number(
      rate
    );


  if (
    !Number.isFinite(
      numericRate
    )
  ) {
    return '';
  }


  // Keep enough precision for currencies such as JPY.
  //
  // Examples:
  // USD -> 31.7640
  // JPY -> 0.2024
  return numericRate.toLocaleString(
    'en-US',
    {
      minimumFractionDigits: 4,
      maximumFractionDigits: 6
    }
  );
}


export function formatTwdAmount(
  amount
) {

  const numericAmount =
    Number(
      amount
    );


  if (
    !Number.isFinite(
      numericAmount
    )
  ) {
    return '';
  }


  return numericAmount.toLocaleString(
    'en-US',
    {
      minimumFractionDigits: 0,
      maximumFractionDigits: 2
    }
  );
}


// =========================================================
// Display label helper
// =========================================================

export function getFxSourceLabel(
  fxReference
) {

  if (
    !fxReference ||
    !fxReference.available
  ) {
    return '';
  }


  if (
    fxReference.source ===
    'First Bank'
  ) {
    return '第一銀行參考匯率';
  }


  if (
    fxReference.source ===
    'Mastercard'
  ) {
    return 'Mastercard 參考匯率';
  }


  if (
    fxReference.source ===
    'Visa'
  ) {
    return 'Visa 參考匯率';
  }


  return '參考匯率';
}


// =========================================================
// Build display-ready FX data
// =========================================================

export function buildFxDisplay(
  fxReference,
  foreignAmount
) {

  if (
    !fxReference ||
    !fxReference.available
  ) {
    return null;
  }


  const convertedAmount =
    convertToTwd(
      foreignAmount,
      fxReference.rate
    );


  if (
    convertedAmount === null
  ) {
    return null;
  }


  return {
    network:
      fxReference.network,

    source:
      fxReference.source,

    sourceLabel:
      getFxSourceLabel(
        fxReference
      ),

    referenceDate:
      fxReference.referenceDate,

    formattedReferenceDate:
      formatFxDate(
        fxReference.referenceDate
      ),

    currency:
      fxReference.currency,

    homeCurrency:
      fxReference.homeCurrency,

    rate:
      fxReference.rate,

    formattedRate:
      formatFxRate(
        fxReference.rate
      ),

    foreignAmount:
      Number(
        foreignAmount
      ),

    convertedAmount,

    formattedConvertedAmount:
      formatTwdAmount(
        convertedAmount
      ),

    fallbackUsed:
      fxReference.fallbackUsed,

    daysBack:
      fxReference.daysBack
  };
}
